language: python
sudo: required
dist: xenial

services:
    - xvfb

python:
  - "3.5"
  - "3.6"
  - "3.7"

cache: pip

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run pip install PyQt5 PySide2

script:
  - pipenv run flake8 asyncqt
  - QT_API=PyQt5 xvfb-run pipenv run py.test -v --cov=asyncqt
  - QT_API=PySide2 xvfb-run pipenv run py.test -v --cov=asyncqt

after_success:
  - codecov
